//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steward.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_EN
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_EN()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steward.Localization.Strings-EN", typeof(Strings_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank you! Please remember that you can carry on asking more questions.
        /// </summary>
        internal static string AfterRating
        {
            get
            {
                return ResourceManager.GetString("AfterRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Good Evening to you out there :)
        ///**how can I help you?**
        ///
        ///*you can just type in your query, you need help in.*.
        /// </summary>
        internal static string GoodEveningMessage
        {
            get
            {
                return ResourceManager.GetString("GoodEveningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Very good morning to you too!
        ///**how can I help you?**
        ///
        ///*you can just type in your query, you need help in.*.
        /// </summary>
        internal static string GoodMorningMessage
        {
            get
            {
                return ResourceManager.GetString("GoodMorningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to you have a good night too!
        ///
        ///*you can just type in your query, you need help in.*.
        /// </summary>
        internal static string GoodNightMessage
        {
            get
            {
                return ResourceManager.GetString("GoodNightMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hi thanks for dropping by!
        ///**how can I help you?**
        ///
        ///*you can just type in your query, you need help in.*.
        /// </summary>
        internal static string GreetingMessage
        {
            get
            {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hi!, I&apos;m Steward, i try to help you to get answers for some of the issues and queries that you have for the help desk,
        ///
        ///you can ask me questions like: where to download Eikon? etc.
        ///
        ///you can get more information @ [Steward Help](#https://thehub.thomsonreuters.com/docs/DOC-2145793).
        /// </summary>
        internal static string HelpMessage
        {
            get
            {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry I did not understand: you can ask me questions like: 
        ///where to download Eikon? etc.
        ///you can always enter **Help** to get more info..
        /// </summary>
        internal static string NoneIntent
        {
            get
            {
                return ResourceManager.GetString("NoneIntent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, I wasn&apos;t able to find anything in the Knowledge Base. I&apos;ve made a note and will try to get this added moving forwards..
        /// </summary>
        internal static string NotFoundInKb
        {
            get
            {
                return ResourceManager.GetString("NotFoundInKb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #H1 Thanks for your feedback. 
        ///
        ///Please rate this service between 1 to 5, 1 being unsatisfactory, 5 being excellent.
        /// </summary>
        internal static string PromptRating
        {
            get
            {
                return ResourceManager.GetString("PromptRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thanks for dropping by! 
        ///
        ///If you would like to **rate** us, please type **Feedback** then follow with your feedback
        ///
        ///Remember you can always ask me new queries at any time..
        /// </summary>
        internal static string ThanksMessage
        {
            get
            {
                return ResourceManager.GetString("ThanksMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #H4 Please check if the &quot;Thomson Reuters&quot; AddIn is disabled or deactivated
        ///
        ///*To check please follow the steps:*
        ///1. Go to File -&gt; Excel Options -&gt; Add-ins 
        ///2. Check if &quot;Thomson Reuters Eikon - Microsoft Office&quot; appears in;     
        ///- Disabled Application Add-ins     
        ///- Inactive Application Add-ins
        ///
        ///**Does it appear under disabled or deactivated?**.
        /// </summary>
        internal static string TRAddInDisabledInactive
        {
            get
            {
                return ResourceManager.GetString("TRAddInDisabledInactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #H4 Is there the &quot;User Account Control (UAC)&quot; pop up when Open Excel?
        ///
        ///*Please follow these steps to Unchecked Privilege Level (Run as Administrator) in case of UAC pop-up*
        ///
        ///Unchecked Privilege Level: 
        ///1. Go to the part of MS Office in Program File (e.g. &quot;C:\Program Files (x86)\Microsoft Office\Office14&quot;) 
        ///2. Find &quot;EXCEL.EXE&quot; 
        ///3. Right-click on it and select &quot;Properties&quot; 
        ///4. Go to tab &quot;Compatibility&quot; and untick &quot;Run this program as an administrtor&quot;
        ///
        ///*Once repair is done* -&gt;**Does these steps resol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TRAddinUAC
        {
            get
            {
                return ResourceManager.GetString("TRAddinUAC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to *Manually add TR Office add-in:* 
        ///1. Go to File -&gt; Excel Options -&gt; Add-ins 
        ///2. Select to manage &quot;COM Add-in&quot; 
        ///3. Click &quot;Add...&quot; and go to Eikon folder; &quot;C:\Program Files (x86)\Thomson Reuters\Eikon&quot; 
        ///4. Add &quot;EikonOfficeShim.dll&quot;
        ///
        ///*Once the configuration is done*-&gt; **Did this solve the issue?**.
        /// </summary>
        internal static string TRAdinConfigureManual
        {
            get
            {
                return ResourceManager.GetString("TRAdinConfigureManual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to **Enable Add-in:** 
        ///1. Go to File -&gt; Excel Options -&gt; Add-ins     
        ///- If Disabled - Select to manage &quot;Disable Items&quot;
        ///- IF Inactive - Select to manage &quot;COM Add-in&quot; 
        ///2. Enable &quot;Thomson Reuters Eikon 
        ///- Microsoft Office&quot; Add-in
        ///
        ///*Once the above steps are followed* -&gt; **Did this solve the issue?**.
        /// </summary>
        internal static string TRAdinEnable
        {
            get
            {
                return ResourceManager.GetString("TRAdinEnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to **Is TR Ribbon incomplete?** *(missing buttons, #NAME? for functions)?*.
        /// </summary>
        internal static string TRMissingMenu
        {
            get
            {
                return ResourceManager.GetString("TRMissingMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please go ahead and **Reinstall MS Office and Eikon.**
        ///
        ///*Once you are through reinstalling*-&gt; **Did that work?**.
        /// </summary>
        internal static string TRReInstall
        {
            get
            {
                return ResourceManager.GetString("TRReInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run **&quot;Repair&quot;** for MS Office via Control Panel.
        /// 
        ///*Once repair is done* -&gt; tell us if that worked?.
        /// </summary>
        internal static string TRRepair
        {
            get
            {
                return ResourceManager.GetString("TRRepair", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Does **&quot;Thomson Reuters&quot;** tab appear in the menu bar?.
        /// </summary>
        internal static string TRTabAppear
        {
            get
            {
                return ResourceManager.GetString("TRTabAppear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #Please contact Technical Support and do remember to have following list handy: 
        ///
        ///**Mandatory details:** 
        ///1. Clear problem statement 
        ///2. Customer Eikon UUID 
        ///3. Reproduction steps
        ///
        ///*Logs to be collected:*
        ///1. Eikon Office Logs: Verbose 
        ///2. Dump Configuration 
        ///3. Procmon logs 
        ///4. Screenshot of issue 
        ///5. VDO recording (optional).
        /// </summary>
        internal static string TRTechSupportMandatory
        {
            get
            {
                return ResourceManager.GetString("TRTechSupportMandatory", resourceCulture);
            }
        }
    }
}
